name: Prevent Supabase Sleep (Daily Ping)

on:
  schedule:
    # 毎日 18:10 (UTC 09:10) に自動実行
    # Supabaseフリープランの自動停止 (7日間無アクセス) を防ぐ
    - cron: "30 9 * * *"
  workflow_dispatch:

jobs:
  make_request:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Tokyo"

    steps:
      - name: Send keep-alive request
        run: |
          curl -X GET "https://progress-lens.vercel.app/api/v1/status" -v --fail || exit 1

      - name: Log keep-alive time
        run: |
          echo "Keep-alive ping completed at $(date)"
